# Generated by Django 2.2 on 2019-04-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20190331_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='fooding',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='insurance',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='lodging',
            field=models.BooleanField(default=0),
        ),
    ]
