# Generated by Django 2.2 on 2019-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_auto_20190404_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='image',
            field=models.ImageField(null=True, upload_to='Vacancies/Image/%Y/%m/%d/'),
        ),
    ]
