# Generated by Django 2.1.5 on 2019-04-01 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_auto_20190331_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 4, 1)),
        ),
        migrations.AddField(
            model_name='leave',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 4, 1)),
        ),
        migrations.AlterField(
            model_name='user',
            name='leave_taken',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
