# Generated by Django 2.2 on 2019-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0006_auto_20190404_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Salary',
            field=models.FloatField(default=None, null=True),
        ),
    ]
