# Generated by Django 2.2 on 2019-04-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0008_auto_20190405_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Salary',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='leave_taken',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
