# Generated by Django 2.2 on 2019-04-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0009_auto_20190405_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='netSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000)),
                ('month', models.IntegerField(default=1)),
                ('doc', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
