# Generated by Django 2.2 on 2019-04-05 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0010_netsalary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netsalary',
            name='doc',
        ),
        migrations.AddField(
            model_name='netsalary',
            name='employee',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='netsalary',
            name='netSal',
            field=models.FloatField(default=0),
        ),
    ]
