# Generated by Django 2.2 on 2019-04-06 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0012_auto_20190405_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='netsalary',
            name='given',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leave',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 4, 6, 11, 35, 26, 157000)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 4, 6, 11, 35, 26, 156786)),
        ),
    ]
