# Generated by Django 2.2 on 2019-04-06 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0014_auto_20190406_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='netsalary',
            name='leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='TotalSalary',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 4, 6, 13, 22, 58, 273808)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 4, 6, 13, 22, 58, 273614)),
        ),
    ]
