# Generated by Django 2.2 on 2019-04-07 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0016_auto_20190407_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=55)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='leave',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 4, 7, 18, 46, 16, 302808)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 4, 7, 18, 46, 16, 302588)),
        ),
    ]
